configs:
  cm:
    url: "https://cd.${dns_zone}"
    server.rbac.log.enforce.enable: "true"
    exec.enabled: "true"
    admin.enabled: "true"
  params:
    server.insecure: true
  rbac:
    policy.default: role:readonly

server:
  replicas: 3
  env:
    - name: ARGOCD_API_SERVER_REPLICAS
      value: "3"
  pdb:
    minAvailable: 1
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
  service:
    annotations:
      # projectcontour.io/upstream-protocol.tls: "444" # requires configs.params.server.insecure=false
  ingress:
    enabled: true
    https: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod-${class}
      ingress.kubernetes.io/force-ssl-redirect: "true" # not required if you do tls-passthrough
    ingressClassName: ${class}
    hosts:
      - cd.${dns_zone}
    tls:
      - secretName: argocd-tls
        hosts:
          - cd.${dns_zone}
  priorityClassName: "system-cluster-critical"
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
    readOnlyRootFilesystem: true
    runAsNonRoot: true
  metrics:
    enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi

  controller:
    replicas: 2
    env:
      - name: ARGOCD_CONTROLLER_REPLICAS
        value: "2"
    enableStatefulSet: true
    priorityClassName: "system-cluster-critical"
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      readOnlyRootFilesystem: true
      runAsNonRoot: true
    metrics:
      enabled: true
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 50m
        memory: 128Mi

  notifications:
    priorityClassName: "system-cluster-critical"
    containerSecurityContext:
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - ALL
    metrics:
      enabled: true
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 64Mi

  redis:
    priorityClassName: "system-cluster-critical"
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      readOnlyRootFilesystem: true
      runAsNonRoot: true
    metrics:
      enabled: true
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 5m
          memory: 16Mi
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 64Mi

  repoServer:
    replicas: 3
    priorityClassName: "system-cluster-critical"
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      readOnlyRootFilesystem: true
      runAsNonRoot: true
    metrics:
      enabled: true
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 50m
        memory: 64Mi

  applicationSet:
    priorityClassName: "system-cluster-critical"
    containerSecurityContext:
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - ALL
    metrics:
      enabled: true
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 64Mi