serviceAccount:
  name: ${sa_name}
  annotations:
    eks.amazonaws.com/role-arn: ${role_arn}
env:
  - name: AWS_DEFAULT_REGION
    value: ${region}
triggerLoopOnEvent: true
policy: sync
txtOwnerId: ${cluster_name}
provider: aws